name: sr_java_spring

services:
  db:
    image: postgres:16.8-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: sr_java_spring
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
  queue:
    image: rabbitmq:3.13.7
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5673:5672